import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { CalendarComponent } from '@/components/Calendar';
import { UIProvider } from '@/providers/UIProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <UIProvider className="w-full h-full">
                    <main className="h-full dark text-foreground bg-background">{children}</main>
                </UIProvider>
            </body>
        </html>
    );
}
