import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { UIProvider } from '@/providers/UIProvider';
import { CalendarWrapper } from '@/components/CalendarWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <UIProvider className="w-full h-full">
                    <main className="h-full dark text-foreground bg-background">
                        <CalendarWrapper />
                        {children}
                    </main>
                </UIProvider>
            </body>
        </html>
    );
}
